rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('about/', views.about, name = 'about'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from rango import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('', views.about, name = 'about'),
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from rango.models import Page, Category
from django.contrib.auth.models import User
from rango.models import UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url

        return cleaned_data

    class Meta:
        model = Page
        exclude = ('category',)

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)

rango/views.py
from django.shortcuts import render
from django.http import HttpResponse
from rango.models import Category, Page
from rango.forms import CategoryForm
from django.shortcuts import redirect
from rango.forms import PageForm
from django.urls import reverse
from rango.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from datetime import datetime

def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]

    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list

    visitor_cookie_handler(request)
    response = render(request, 'rango/index.html', context=context_dict)
    return response

def about(request):
    visitor_cookie_handler(request)
    context_dict = {'visits': request.session['visits']}
    response = render(request, 'rango/about.html', context=context_dict)
    return response

def show_category(request, category_name_slug):
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict['pages'] = pages
        context_dict['category'] = category

    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None

    return render(request, 'rango/category.html', context=context_dict)

@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            cat = form.save(commit=True)
            print(cat, cat.slug)
            return redirect('/rango/')

        else:
            print(form.errors)

    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)

    except Category.DoesNotExist:
        category = None

    if category is None:
        return redirect('/rango/')

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()

                return redirect(reverse('rango:show_category', kwargs={'category_name_slug': category_name_slug}))

        else:
            print(form.errors)

    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'rango/register.html', context = {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('rango:index'))

            else:
                return HttpResponse("Your Rango account is disabled.")

        else:
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")

    else:
        return render(request, 'rango/login.html')

def some_view(request):
    if not request.user.is_authenticated():
        return HttpResponse("You are logged in.")

    else:
        return HttpResponse("You are not logged in.")

@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')

@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('rango:index'))

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())

    else:
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  About Rango
{% endblock %}

{% block body_block %}
  <h1>Rango says...</h1>
  <div>
    here is the about page.<br />
    <p>Visits: {{ visits }}</p>
    <strong>This tutorial has been put together by Leighton Guang</strong><br />
  </div>

  <div>
    <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
    <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat." />
  </div>
{% endblock %}



<!--
<!DOCTYPE html>

{% load staticfiles %}

<html>

  <head>
    <title>Rango</title>
  </head>

  <body>
    <h1>Rango says...</h1>
    <div>
      here is the about page.<br />
      <strong>This tutorial has been put together by Leighton Guang</strong><br />
    </div>

    <div>
      <a href="/rango/about/">About</a><br />
      <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
      <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat." />
    </div>
  </body>

</html>
-->

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  Add a Category
{% endblock %}

{% block body_block %}
  <h1>Add a Category</h1>
  <div>
    <form id="category_form" method="post" action="/rango/add_category/">
      {% csrf_token %}
      {% for hidden in form.hidden_fields %}
          {{ hidden }}
      {% endfor %}
      {% for field in form.visible_fields %}
          {{ field.errors }}
          {{ field.help_text }}
          {{ field }}
      {% endfor %}
      <input type="submit" name="submit" value="Create Category" />
    </form>
  </div>
{% endblock %}


<!--
<!DOCTYPE html>
<html>
  <head>
    <title>Rango</title>
  </head>

  <body>
      <h1>Add a Category</h1>
      <div>
        <form id="category_form" method="post" action="/rango/add_category/">
          {% csrf_token %}
          {% for hidden in form.hidden_fields %}
              {{ hidden }}
          {% endfor %}
          {% for field in form.visible_fields %}
              {{ field.errors }}
              {{ field.help_text }}
              {{ field }}
          {% endfor %}
          <input type="submit" name="submit" value="Create Category" />
        </form>
      </div>
  </body>
</html>
-->

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  Add a Page
{% endblock %}

{% block body_block %}
<div>
    {% if category %}
  <h1>Add a Page to {{category.name}}</h1>
  <form id="page_form" method="post" action="/rango/category/{{ category.slug }}/add_page/">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}
    {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}
        {{ field }}
    {% endfor %}
    <input type="submit" name="submit" value="Add Page" />
  </form>
    {% else %}
    The specified category does not exist!
    {% endif %}

</div>
{% endblock %}


<!--
<html>
  <head>
    <title>Rango</title>
  </head>

  <body>
    <h1>Add a Page to {{category.name}}</h1>
    <div>
      <form id="add_page_form" method="post" action="/rango/category/{{ category.slug }}/add_page/">
        {% csrf_token %}
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}
        <input type="submit" name="submit" value="Add Page" />
      </form>
    </div>

  </body>
</html>
-->

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html>

  <head>
    <title>
      Rango -
      {% block title_block %}
        How to Tango with Django!
      {% endblock %}
    </title>
  </head>

  <body>
    <div>
      {% block body_block %}
      {% endblock %}
    </div>

    <div>
      {% block sidebar_block %}
        {% get_category_list %}
      {% endblock %}
    </div>
    <hr />
    <div>
      <ul>
        {% if user.is_authenticated %}
        <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
        <li><a href="{% url 'rango:logout' %}">Logout</a></li>
        <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
        {% else %}
        <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
        <li><a href="{% url 'rango:login' %}">Login</a></li>
        {% endif %}
        <li><a href="{% url 'rango:about' %}">About</a></li>
        <li><a href="{% url 'rango:index' %}">Index</a></li>
      </ul>
    </div>
  </body>
</html>

templates/rango/categories.html
<ul>
  {% if categories %}
    {% for c in categories%}
      <li><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></li>
    {% endfor %}
  {% else %}
    <li><strong>There are no categories present.</strong></li>
  {% endif %}
</ul>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  {% if category %}
    {{ category.name }}
  {% else %}
    Unknown Category
  {% endif %}
{% endblock %}

{% block body_block %}
  {% if category %}
  <h1>{{ category.name }}</h1>
    {% for c in categories %}
      {% if c == current_category %}
      <li>
        <strong>
          <a href="{% url 'rango;show_category' c.slug %}">{{ c.name }}</a>
        </strong>
      </li>
      {% else %}
        <li>
          <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
        </li>
      {% endif %}
    {% endfor %}
  {% endif %}
  <h1>{{ category.name }}</h1>
  {% if pages %}
    <ul>
      {% for page in pages %}
        <li><a href="{{ page.url }}">{{ page.title }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <strong>No pages currently in category.</strong>
  {% endif %}

  {% if user.is_authenticated %}
    <a href="{% url 'rango:add_page' category.slug %}">Add Page</a> <br/>
  {% else %}
    The specified category does not exist.
  {% endif %}
{% endblock %}



<!--
<!DOCTYPE html>
<html>

  <head>
    <title>Rango</title>
  </head>

  <body>
    <div>
    {% if category %}
      <h1>{{ category.name }}</h1>
      {% if pages %}
      <ul>
        {% for page in pages %}
        <li><a href="{{ page.url }}">{{ page.title }}</a></li>
        {% endfor %}
      </ul>
      {% else %}
      <strong>No pages currently in category.</strong>
      {% endif %}
      <a href="/rango/category/{{ category.slug }}/add_page/">Add Page</a> <br/>
    {% else %}
      The specified category does not exist.
    {% endif %}
    </div>

    <a href="/rango/">Index</a>

  </body>
</html>
-->

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Homepage
{% endblock %}

{% block body_block %}
  <h1>Rango says...</h1>
  <div>
    {% if user.is_authenticated %}
      howdy {{ user.username }}!
    {% else %}
      hey there partner!
    {% endif %}

    <strong>{{ boldmessage }}</strong><br />
  </div>

    <div>
      <h2>Most Liked Categories</h2>
      {% if categories %}
        <ul>
          {% for category in categories %}
            <li><a href="/rango/category/{{ category.slug }}/">{{ category.name }}</a></li>
          {% endfor %}
        </ul>
      {% else %}
        <strong>There are no categories present.</strong>
      {% endif %}
    </div>

    <div>
      <h2>Most Viewed Pages</h2>
      {% if pages %}
        <ul>
          {% for page in pages %}
            <li><a href="{{ page.url }}">{{ page.title }}</a></li>
          {% endfor %}
        </ul>
      {% else %}
        <strong>There are no pages present.</strong>
      {% endif %}
    </div>

    <div>
      <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
    </div>
{% endblock %}



<!--<!DOCTYPE html>

{% load staticfiles %}

<html>

  <head>
    <title>Homepage</title>
  </head>

  <body>
    <h1>Rango says...</h1>

    <div>
      hey there partner! <br />
      <strong>{{ boldmessage }}</strong><br />
    </div>


    <h2>Most Liked Categories</h2>
    <div>
      {% if categories %}
      <ul>
      {% for category in categories %}
      <li>
        <a href="{% url 'rango:show_category' category.slug %}">
          {{ category.name }}
        </a>
      </li>
      {% endfor %}
    </ul>
    {% else %}
      <strong>There are no categories present.</strong>
    {% endif %}
    </div>


    <h2>Most Viewed Pages</h2>
    <div>
      {% if pages %}
      <ul>
      {% for page in pages %}
        <li>
          <a href="{{ page.url }}">{{ page.title }}</a>
        </li>
        {% endfor %}
      </ul>
      {% else %}
        <strong>There are no categories present.</strong>
      {% endif %}
    </div>

    <div>
      <a href="{% url 'rango:about' %}">About</a><br />
      <a href="/rango/add_category/">Add a New Category</a><br />
      <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
    </div>

  </body>

</html>
-->

templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  Login
{% endblock %}

{% block body_block %}
<h1>Login to Rango</h1>
<form id="login_form" method="post" action="{% url 'rango:login' %}">
  {% csrf_token %}
  Username: <input type="text" name="username" value="" size="50" />
  <br />
  Password: <input type="password" name="password" value="" size="50" />
  <br />
  <input type="submit" value="submit" />
</form>
{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
     Register
 {% endblock %}

{% block body_block %}
  <h1>Register for Rango</h1>
{% if registered %}
  Rango says: <strong>thank you for registering!</strong>
  <a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
{% else %}
  Rango says: <strong>register here!</strong><br />
  <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">

    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" name="submit" value="Register" />
</form>
{% endif %}
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  Restricted Page
{% endblock %}

{% block body_block %}
  <h1>Since you're logged in, you can see this text!</h1>
{% endblock %}